"""
Django settings for psy project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^@k94crbqbh-(gdpu0j%-kddl%pjc*okwjttde(ji_3xr&o8u0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1

# Application definition


INSTALLED_APPS = [
    'material.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'psy.frontendpsy',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.linkedin_oauth2',
    'django.contrib.admin',
    'material',
    'material.frontend',
]


PIPELINE_COMPILERS = (
  'react.utils.pipeline.JSXCompiler',
)


MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'psy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/templates/',
	],
        #'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
           		'django.template.context_processors.debug',
                	'django.template.context_processors.i18n',
                	'django.template.context_processors.media',
                	'django.template.context_processors.static',
        	        'django.template.context_processors.tz',
			'django.template.context_processors.request',
			'django.contrib.auth.context_processors.auth',
	                'django.contrib.messages.context_processors.messages',
			#"allauth.account.context_processors.account",
			#"allauth.socialaccount.context_processors.socialaccount",
	       ],
	    'debug': True,
	    'loaders': [
	       'django.template.loaders.filesystem.Loader',
               'django.template.loaders.app_directories.Loader',
            ]
        },
    },
]



WSGI_APPLICATION = 'psy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

"""
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
"""

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# auth and allauth settings
#LOGIN_REDIRECT_URL = '/'
SOCIALACCOUNT_QUERY_EMAIL = True
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_PROVIDERS = \
    {'linkedin_oauth2':
          {'SCOPE': ['r_emailaddress','r_basicprofile'],
           'PROFILE_FIELDS': ['id',
                             'first-name',
                             'last-name',
                             'email-address',
                             'picture-url',
                             'picture-urls::(original)', # picture-urls::(original) is higher resolution
                             'public-profile-url',
                             'skills',
                             'headline',
                             'location',
                             'industry',
                             ]}
    }

#SOCIAL_AUTH_LINKEDIN_KEY = 'oucjbc8puyco'
#SOCIAL_AUTH_LINKEDIN_SECRET = 'LtvWBlx3FUsLg6RE'

#EMAIL_HOST = 'localhost'
#EMAIL_PORT = 1025
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = "antonio.vangi.av@gmail.com"
EMAIL_HOST_PASSWORD = '9Opelcorsa'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'antonio.vangi.av@gmail.com'
SERVER_EMAIL = 'antonio.vangi.av@gmail.com'
